apiVersion: v1
kind: Pod
metadata:
  name: hami-gpu-test
  namespace: default
spec:
  schedulerName: hami-scheduler
  containers:
  - name: gpu-test
    image: ubuntu:20.04
    command: ["/bin/bash", "-c", "sleep 3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem: 2000
        nvidia.com/gpucores: 30
      requests:
        nvidia.com/gpu: 1
        nvidia.com/gpumem: 2000
        nvidia.com/gpucores: 30
  restartPolicy: Never
